### PR TITLE
Moving the lattice settings functions

### PR DESCRIPTION
**Pull request by lmalina**
Only the ones which handle errors
   Destination: `SimulatedCommissioning` class

### CODE REVIEW

**Comment by simoneliuzzo** [comment]
All the changes highlighted by github look ok. However there may be not-changed location where change should have occurred. 

by the way, looking at the code, now also all other calls to methods do_something(SC,...) look like they should become SC.do_something(...)

**Comment by simoneliuzzo** [comment]
I keep reviewing

**Comment by lmalina** [comment]
> All the changes highlighted by github look ok. However there may be not-changed location where change should have occurred.
> 
> by the way, looking at the code, now also all other calls to methods do_something(SC,...) look like they should become SC.do_something(...)

Yes, some more functions could be included in the class.  On the other hand, already like this, it is not exactly a small class.

**Comment by simoneliuzzo** [comment]
in bba.py there are some not correct get_cm_setpoints. I guess this is fixed within the bba branch.

**Comment by lmalina** [comment]
> in bba.py there are some not correct get_cm_setpoints. I guess this is fixed within the bba branch.

Exactly, already done in fixing_bba branch.

**Comment by simoneliuzzo** [comment]
I used the pycharm feature "Find in Files" and I could not find any bad useage of:
set_cavity_setpoints

get_cm_setpoints

set_cm_setpoints

set_magnet_setpoints

_dipole_compensation

**Review by simoneliuzzo — APPROVED** [review]

**Pull request merged**
